//
// Generated file, do not edit! Created by nedtool 5.7 from flexe/messages/FlexeMessage.msg.
//

#ifndef __FLEXEMESSAGE_M_H
#define __FLEXEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef FLEXE_API
#  if defined(FLEXE_EXPORT)
#    define FLEXE_API  OPP_DLLEXPORT
#  elif defined(FLEXE_IMPORT)
#    define FLEXE_API  OPP_DLLIMPORT
#  else
#    define FLEXE_API
#  endif
#endif



class FlexeMessage;
#include "veins/modules/messages/DemoSafetyMessage_m.h" // import veins.modules.messages.DemoSafetyMessage

/**
 * Class generated from <tt>flexe/messages/FlexeMessage.msg:3</tt> by nedtool.
 * <pre>
 * packet FlexeMessage extends veins::BaseFrame1609_4
 * {
 *     int senderID = -1;
 *     string model;
 *     long msgId;
 *     double sendTime;
 *     string dataset;
 *     string scenario;
 *     int seed;
 *     bool nonIID;
 *     int idModel;
 *     bool trainFlag;
 *     bool dynamicEpoch = false;
 *     int numClients;
 *     double percentDataset;
 *     int numExamples;
 *     int modelVersion;
 *     string clientSelection;
 *     double loss;
 *     double accuracy;
 * 
 *     double precision;
 *     double recall;        // Sensibilidade (Recall)
 *     double f1Score;
 *     double mcc;           // Matthews Correlation Coefficient
 *     double aucRoc;        // Área sob a curva ROC
 * 
 *     // Matriz de Confusão (Geralmente enviamos os componentes básicos)
 *     int tp; // True Positives
 *     int fp; // False Positives
 *     int tn; // True Negatives
 *     int fn; // False Negatives
 *     double entropy;
 *     double computationCapability;
 *     double computationRequirement;
 *     double roundDeadline;
 *     string color;
 * }
 * </pre>
 */
class FLEXE_API FlexeMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int senderID = -1;
    omnetpp::opp_string model;
    long msgId = 0;
    double sendTime = 0;
    omnetpp::opp_string dataset;
    omnetpp::opp_string scenario;
    int seed = 0;
    bool nonIID = false;
    int idModel = 0;
    bool trainFlag = false;
    bool dynamicEpoch = false;
    int numClients = 0;
    double percentDataset = 0;
    int numExamples = 0;
    int modelVersion = 0;
    omnetpp::opp_string clientSelection;
    double loss = 0;
    double accuracy = 0;
    double precision = 0;
    double recall = 0;
    double f1Score = 0;
    double mcc = 0;
    double aucRoc = 0;
    int tp = 0;
    int fp = 0;
    int tn = 0;
    int fn = 0;
    double entropy = 0;
    double computationCapability = 0;
    double computationRequirement = 0;
    double roundDeadline = 0;
    omnetpp::opp_string color;

  private:
    void copy(const FlexeMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FlexeMessage&);

  public:
    FlexeMessage(const char *name=nullptr, short kind=0);
    FlexeMessage(const FlexeMessage& other);
    virtual ~FlexeMessage();
    FlexeMessage& operator=(const FlexeMessage& other);
    virtual FlexeMessage *dup() const override {return new FlexeMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSenderID() const;
    virtual void setSenderID(int senderID);
    virtual const char * getModel() const;
    virtual void setModel(const char * model);
    virtual long getMsgId() const;
    virtual void setMsgId(long msgId);
    virtual double getSendTime() const;
    virtual void setSendTime(double sendTime);
    virtual const char * getDataset() const;
    virtual void setDataset(const char * dataset);
    virtual const char * getScenario() const;
    virtual void setScenario(const char * scenario);
    virtual int getSeed() const;
    virtual void setSeed(int seed);
    virtual bool getNonIID() const;
    virtual void setNonIID(bool nonIID);
    virtual int getIdModel() const;
    virtual void setIdModel(int idModel);
    virtual bool getTrainFlag() const;
    virtual void setTrainFlag(bool trainFlag);
    virtual bool getDynamicEpoch() const;
    virtual void setDynamicEpoch(bool dynamicEpoch);
    virtual int getNumClients() const;
    virtual void setNumClients(int numClients);
    virtual double getPercentDataset() const;
    virtual void setPercentDataset(double percentDataset);
    virtual int getNumExamples() const;
    virtual void setNumExamples(int numExamples);
    virtual int getModelVersion() const;
    virtual void setModelVersion(int modelVersion);
    virtual const char * getClientSelection() const;
    virtual void setClientSelection(const char * clientSelection);
    virtual double getLoss() const;
    virtual void setLoss(double loss);
    virtual double getAccuracy() const;
    virtual void setAccuracy(double accuracy);
    virtual double getPrecision() const;
    virtual void setPrecision(double precision);
    virtual double getRecall() const;
    virtual void setRecall(double recall);
    virtual double getF1Score() const;
    virtual void setF1Score(double f1Score);
    virtual double getMcc() const;
    virtual void setMcc(double mcc);
    virtual double getAucRoc() const;
    virtual void setAucRoc(double aucRoc);
    virtual int getTp() const;
    virtual void setTp(int tp);
    virtual int getFp() const;
    virtual void setFp(int fp);
    virtual int getTn() const;
    virtual void setTn(int tn);
    virtual int getFn() const;
    virtual void setFn(int fn);
    virtual double getEntropy() const;
    virtual void setEntropy(double entropy);
    virtual double getComputationCapability() const;
    virtual void setComputationCapability(double computationCapability);
    virtual double getComputationRequirement() const;
    virtual void setComputationRequirement(double computationRequirement);
    virtual double getRoundDeadline() const;
    virtual void setRoundDeadline(double roundDeadline);
    virtual const char * getColor() const;
    virtual void setColor(const char * color);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FlexeMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FlexeMessage& obj) {obj.parsimUnpack(b);}

#endif // ifndef __FLEXEMESSAGE_M_H

