[General]
cmdenv-express-mode = true
cmdenv-autoflush = true
cmdenv-status-frequency = 1s
**.cmdenv-log-level = info

repeat = 30
seed-set = ${repetition}

image-path = ../../images

network = GridFlexeScenario

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = true
print-undisposed = true

sim-time-limit = 200s

**.scalar-recording = true
**.vector-recording = true

*.playgroundSizeX = 1000m
*.playgroundSizeY = 1000m
*.playgroundSizeZ = 50m

##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true

##########################################################
#            TraCIScenarioManager parameters             #
##########################################################
*.manager.updateInterval = 1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.manager.allowPedestrians = false

##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################
*.rsu[0].mobility.x = 500
*.rsu[0].mobility.y = 500
*.rsu[0].mobility.z = 3

*.rsu[*].applType = "FedLimRSU11p"
*.rsu[*].appl.headerLength = 80 bit
*.rsu[*].appl.sendBeacons = false
*.rsu[*].appl.dataOnSch = false
*.rsu[*].appl.beaconUserPriority = 7
*.rsu[*].appl.dataUserPriority = 5
*.rsu[*].nic.phy80211p.antennaOffsetZ = 0 m

*.rsu[*].appl.model = "GENERIC_MODEL"
*.rsu[*].appl.dataset = "MNIST"
*.rsu[*].appl.scenario = "GRID"
*.rsu[*].appl.seed = 42
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.trainFlag = true
*.rsu[*].appl.epochs = 1
*.rsu[*].appl.batch = 1024
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.strategy = "FED_AVG"
*.rsu[*].appl.computationRequirement = "900"
*.rsu[*].appl.roundDeadline = 1.0
*.rsu[*].appl.K = 0.1
*.rsu[*].appl.address = "127.0.0.1:5000"

##########################################################
#            11p specific parameters                     #
#                                                        #
#                    NIC-Settings                        #
##########################################################
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

#312 m
*.node[*].nic.mac1609_4.txPower = 15mW
*.node[*].nic.mac1609_4.bitrate = 6Mbps
*.node[*].nic.phy80211p.minPowerLevel = -86dBm

#5726 m
*.rsu[*].nic.mac1609_4.txPower = 20mW
*.rsu[*].nic.mac1609_4.bitrate = 6Mbps
*.rsu[*].nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config_no_obstacle.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config_no_obstacle.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m

##########################################################
#                      App Layer                         #
##########################################################
*.node[*].applType = "MLApp"
*.node[*].appl.headerLength = 80 bit
*.node[*].appl.sendBeacons = true
*.node[*].appl.dataOnSch = false
*.node[*].appl.beaconInterval = 0.1s # 10Hz

*.node[*].appl.epochs = 5
*.node[*].appl.batch = 32
*.node[*].appl.computationCapability = uniform(0.5GHz, 4GHz)
*.node[*].appl.address = "127.0.0.1:5000"
*.node[*].appl.speedZero = false
##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 0

###############################################################
###############################################################
[Config IID_MNIST_LOW_STATIC] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_LOWSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"

[Config IID_MNIST_LOW] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_LOW"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"

[Config IID_MoreRounds_MNIST_LOW] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_MOREROUNDSLOW"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"

[Config NonIID_MNIST_LOW_STATIC] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 40
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_LOWSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"

[Config NonIID_MNIST_LOW] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 40
*.rsu[*].appl.scenario = "GRID_LOW"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"

[Config NonIID_MoreRounds_MNIST_LOW] #OK
*.manager.launchConfig = xmldoc("seeds/40_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 40
*.rsu[*].appl.scenario = "GRID_MOREROUNDSLOW"
*.rsu[*].appl.address = "127.0.0.1:5002"
*.node[*].appl.address = "127.0.0.1:5002"
###############################################################
###############################################################
[Config IID_MNIST_MEDIUM_STATIC]
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_MEDIUMSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"

[Config IID_MNIST_MEDIUM]
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_MEDIUM"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"

[Config IID_MoreRounds_MNIST_MEDIUM]
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_MOREROUNDSMEDIUM"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"

[Config NonIID_MNIST_MEDIUM_STATIC]
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 100
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_MEDIUMSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"

[Config NonIID_MNIST_MEDIUM]
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 100
*.rsu[*].appl.scenario = "GRID_MEDIUM"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"

[Config NonIID_MoreRounds_MNIST_MEDIUM] 
*.manager.launchConfig = xmldoc("seeds/100_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 100
*.rsu[*].appl.scenario = "GRID_MOREROUNDSMEDIUM"
*.rsu[*].appl.address = "127.0.0.1:5003"
*.node[*].appl.address = "127.0.0.1:5003"
###############################################################
###############################################################
[Config IID_MNIST_HIGH_STATIC]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_HIGHSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"

[Config IID_MNIST_HIGH]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_HIGH"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"

[Config IID_MoreRounds_MNIST_HIGH]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = false
*.rsu[*].appl.numClients = 1
*.rsu[*].appl.scenario = "GRID_MOREROUNDSHIGH"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"

[Config NonIID_MNIST_HIGH_STATIC]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 200
*.node[*].appl.speedZero = true
*.rsu[*].appl.scenario = "GRID_HIGHSTATIC"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"

[Config NonIID_MNIST_HIGH]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 200
*.rsu[*].appl.scenario = "GRID_HIGH"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"

[Config NonIID_MoreRounds_MNIST_HIGH]
*.manager.launchConfig = xmldoc("seeds/200_${repetition}.launchd.xml")
*.rsu[*].appl.seed = ${repetition}
*.rsu[*].appl.roundDeadline = 0.5
*.rsu[*].appl.nonIID = true
*.rsu[*].appl.numClients = 200
*.rsu[*].appl.scenario = "GRID_MOREROUNDSHIGH"
*.rsu[*].appl.address = "127.0.0.1:5004"
*.node[*].appl.address = "127.0.0.1:5004"